// Code generated by protoc-gen-go.
// source: mysqlx_connection.proto
// DO NOT EDIT!

/*
Package Mysqlx_Connection is a generated protocol buffer package.

It is generated from these files:
	mysqlx_connection.proto

It has these top-level messages:
	Capability
	Capabilities
	CapabilitiesGet
	CapabilitiesSet
	Close
*/
package Mysqlx_Connection

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import "github.com/sjmudd/go-mysqlx-driver/Mysqlx_Datatypes"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
const _ = proto.ProtoPackageIsVersion1

// a Capability
//
// a tuple of a ``name`` and a :protobuf:msg:`Mysqlx.Datatypes::Any`
type Capability struct {
	Name             *string               `protobuf:"bytes,1,req,name=name" json:"name,omitempty"`
	Value            *Mysqlx_Datatypes.Any `protobuf:"bytes,2,req,name=value" json:"value,omitempty"`
	XXX_unrecognized []byte                `json:"-"`
}

func (m *Capability) Reset()                    { *m = Capability{} }
func (m *Capability) String() string            { return proto.CompactTextString(m) }
func (*Capability) ProtoMessage()               {}
func (*Capability) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Capability) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

func (m *Capability) GetValue() *Mysqlx_Datatypes.Any {
	if m != nil {
		return m.Value
	}
	return nil
}

// Capabilities
type Capabilities struct {
	Capabilities     []*Capability `protobuf:"bytes,1,rep,name=capabilities" json:"capabilities,omitempty"`
	XXX_unrecognized []byte        `json:"-"`
}

func (m *Capabilities) Reset()                    { *m = Capabilities{} }
func (m *Capabilities) String() string            { return proto.CompactTextString(m) }
func (*Capabilities) ProtoMessage()               {}
func (*Capabilities) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Capabilities) GetCapabilities() []*Capability {
	if m != nil {
		return m.Capabilities
	}
	return nil
}

// get supported connection capabilities and their current state
//
//   :returns: :protobuf:msg:`Mysqlx.Connection::Capabilities` or :protobuf:msg:`Mysqlx::Error`
//
type CapabilitiesGet struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *CapabilitiesGet) Reset()                    { *m = CapabilitiesGet{} }
func (m *CapabilitiesGet) String() string            { return proto.CompactTextString(m) }
func (*CapabilitiesGet) ProtoMessage()               {}
func (*CapabilitiesGet) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

// sets connection capabilities atomically
//
// only provided values are changed, other values are left unchanged.
// If any of the changes fails, all changes are discarded.
//
// :precond: active sessions == 0
// :returns: :protobuf:msg:`Mysqlx::Ok` or :protobuf:msg:`Mysqlx::Error`
type CapabilitiesSet struct {
	Capabilities     *Capabilities `protobuf:"bytes,1,req,name=capabilities" json:"capabilities,omitempty"`
	XXX_unrecognized []byte        `json:"-"`
}

func (m *CapabilitiesSet) Reset()                    { *m = CapabilitiesSet{} }
func (m *CapabilitiesSet) String() string            { return proto.CompactTextString(m) }
func (*CapabilitiesSet) ProtoMessage()               {}
func (*CapabilitiesSet) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *CapabilitiesSet) GetCapabilities() *Capabilities {
	if m != nil {
		return m.Capabilities
	}
	return nil
}

// announce to the server that the client wants to close the connection
//
// it discards any session state of the server
//
// :Returns: :protobuf:msg:`Mysqlx::Ok`
type Close struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *Close) Reset()                    { *m = Close{} }
func (m *Close) String() string            { return proto.CompactTextString(m) }
func (*Close) ProtoMessage()               {}
func (*Close) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func init() {
	proto.RegisterType((*Capability)(nil), "Mysqlx.Connection.Capability")
	proto.RegisterType((*Capabilities)(nil), "Mysqlx.Connection.Capabilities")
	proto.RegisterType((*CapabilitiesGet)(nil), "Mysqlx.Connection.CapabilitiesGet")
	proto.RegisterType((*CapabilitiesSet)(nil), "Mysqlx.Connection.CapabilitiesSet")
	proto.RegisterType((*Close)(nil), "Mysqlx.Connection.Close")
}

var fileDescriptor0 = []byte{
	// 213 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xe2, 0x12, 0xcf, 0xad, 0x2c, 0x2e,
	0xcc, 0xa9, 0x88, 0x4f, 0xce, 0xcf, 0xcb, 0x4b, 0x4d, 0x2e, 0xc9, 0xcc, 0xcf, 0xd3, 0x2b, 0x28,
	0xca, 0x2f, 0xc9, 0x17, 0x12, 0xf4, 0x05, 0x4b, 0xe8, 0x39, 0xc3, 0x25, 0xa4, 0xc4, 0xa0, 0x6a,
	0x53, 0x12, 0x4b, 0x12, 0x4b, 0x2a, 0x0b, 0x52, 0x8b, 0x21, 0x4a, 0x95, 0x1c, 0xb8, 0xb8, 0x9c,
	0x13, 0x0b, 0x12, 0x93, 0x32, 0x73, 0x32, 0x4b, 0x2a, 0x85, 0x78, 0xb8, 0x58, 0xf2, 0x12, 0x73,
	0x53, 0x25, 0x18, 0x15, 0x98, 0x34, 0x38, 0x85, 0x54, 0xb8, 0x58, 0xcb, 0x12, 0x73, 0x4a, 0x53,
	0x25, 0x98, 0x80, 0x5c, 0x6e, 0x23, 0x51, 0x3d, 0xa8, 0xb1, 0x2e, 0x70, 0x33, 0x1c, 0xf3, 0x2a,
	0x95, 0x9c, 0xb9, 0x78, 0xe0, 0x26, 0x64, 0xa6, 0x16, 0x0b, 0x19, 0x73, 0xf1, 0x24, 0x23, 0xf1,
	0x81, 0x66, 0x31, 0x03, 0x35, 0xcb, 0xea, 0x61, 0xb8, 0x49, 0x0f, 0x61, 0xb1, 0x92, 0x20, 0x17,
	0x3f, 0xb2, 0x21, 0xee, 0xa9, 0x25, 0x4a, 0x1e, 0xa8, 0x42, 0xc1, 0xa9, 0x25, 0x42, 0xa6, 0x18,
	0x46, 0x83, 0xdc, 0x25, 0x8f, 0xcf, 0x68, 0xa0, 0x32, 0x25, 0x76, 0x2e, 0x56, 0xe7, 0x9c, 0xfc,
	0xe2, 0x54, 0x27, 0x39, 0x2e, 0x99, 0xe4, 0xfc, 0x5c, 0x3d, 0x70, 0x50, 0xe8, 0x25, 0x67, 0x41,
	0x18, 0x15, 0x90, 0x90, 0x48, 0x2a, 0x4d, 0x03, 0x04, 0x00, 0x00, 0xff, 0xff, 0x96, 0xbd, 0xe1,
	0x56, 0x51, 0x01, 0x00, 0x00,
}
